#!/bin/bash

# change to the package directory
cd /root/zarf-package/

# define the pod name or pattern to search for
POD_NAME="argocd"

# check for the pod
POD_CHECK=$(kubectl get pods -n argocd --output=name | grep "$POD_NAME")

# check if pod was found
if [ -z "$POD_CHECK" ]; then
    fail-message "ArgoCD deployment not found"
else
    echo "ArgoCD deployment found"
fi