#!/bin/bash

# Define the pod name or pattern to search for
POD_NAME="wordpress"

# Check for the pod
POD_CHECK=$(kubectl get pods -n wordpress --no-headers custom-columns=":metadata.name" | grep "^$POD_NAME")

# Chek if pod was found
if [ -z "$POD_CHECK" ]; then
    fail-message "WordPress deployment not found"
else
    echo "WordPress deployment found"
fi