#!/bin/bash

# Change to the package directory
cd /root/zarf-package/

# Deploy the Zarf package
zarf package deploy $(ls "zarf-package-wordpress-amd64"* | head -n 1) --set WORDPRESS_PASSWORD="zarf" --confirm