#!/bin/bash

# Change to package directory
cd /root/zarf-package/

# Define the file pattern
file_pattern="zarf-package-wordpress-amd64*"

# Check if any file matching the pattern exists
if ls $file_pattern 1> /dev/null 2>&1; then
    echo "A file matching the pattern 'zarf-package-wordpress-amd64*' was found."
else
    fail-message "Zarf package file not found."
fi