#!/bin/bash

# Setup working directory and zarf.yaml
mkdir /root/zarf-package/
cat > /root/zarf-package/zarf.yaml << EOF
# Zarf Package YAML
EOF
cat > /root/zarf-package/wordpress-values.yaml << EOF
# WordPress Values File
EOF
cat > /root/zarf-package/connect-services.yaml << EOF
# Connect Services File
EOF