#!/bin/bash

# move to correct working directory
cd /root/zarf-package/

# # remove current package files
rm zarf.yaml baseline-values.yaml

# download package files from github
wget https://https://raw.githubusercontent.com/zarf-dev/tutorial/main/01-create-zarf-package/solution/zarf.yaml
wget https://https://raw.githubusercontent.com/zarf-dev/tutorial/main/01-create-zarf-package/solution/baseline-values.yaml

# create package
zarf package create . --confirm
