#!/bin/bash

# define the pod name or pattern to search for
POD_NAME="argocd"

# check for the pod
POD_CHECK=$(kubectl get pods -n argocd --output=name | grep "$POD_NAME")

# check if pod was found
if [ -z "$POD_CHECK" ]; then
    echo "ArgoCD deployment removed successfully"
else
    fail-message "ArgoCD deployment found - not removed successfully"
fi